# Default values for gitops-helm-demo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

image:
  repository: 634072196806.dkr.ecr.cn-north-1.amazonaws.com.cn/gitops-app
  version: 3584ebc