apiVersion: v1
kind: Service
metadata:
  name: gitops-example
  namespace: gitops-cicd
  labels:
    app: gitops-example
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: gitops-example
