---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: gitops-helm-demo
  namespace: gitops-helm
  annotations:
    flux.weave.works/automated: "true"
spec:
  releaseName: gitops-helm-demo
  chart:
    git: git@github.com:terrificdm/gitops-config
    ref: master
    path: charts/gitops-helm-demo
  values:
    image:
      repository: 634072196806.dkr.ecr.cn-north-1.amazonaws.com.cn/gitops-app
      tag: 145d0eb

